# Generated by Django 3.2.8 on 2021-10-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silo_mac', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('datetime_fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
