# Generated by Django 3.2.3 on 2021-11-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='silo_mac',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SiloFeedWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('datetime_fetched', models.DateTimeField()),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silo_feed_weights', to='silo.silo')),
            ],
        ),
    ]
